# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.Department', verbose_name='DPName'),
        ),
    ]
